import {causeLabels,stateLabels} from '../../src/registry-labels.mjs';
export function directoryPage(registry,esc){
  const fmt=n=>n.toLocaleString('en-US');
  return `<section class="directory-hero"><div class="eyebrow"><span class="dot"></span> The charity registry · Beta</div><h1>A much bigger map<br>of <em>possible change.</em></h1><p>Find an organization. Inspect its public record. Help trace the pathway from its work to lasting change.</p><div class="directory-metrics"><div><b>${fmt(registry.recordCount)}</b><span>IRS-listed 501(c)(3) organizations</span></div><div><b>40</b><span>preliminary assessment profiles</span></div><div><b>${Object.keys(registry.causes).length}</b><span>cause classifications</span></div></div></section>
  <div class="registry-bridge"><div><strong>Registration opens the investigation.</strong><p>Registry records have no systemic-impact score yet. Explore the <a href="/#explore">40 preliminary assessments</a> to compare documented mechanisms and evidence gaps.</p></div><a class="button secondary" href="/#explore">Compare systemic potential ↗</a></div>
  <section class="directory-board" aria-labelledby="directory-title"><div class="board-head"><div><div class="eyebrow">Find your starting point</div><h2 id="directory-title">Search the charity index</h2></div><span class="snapshot-tag">IRS snapshot · ${esc(registry.sourcePostedAt)}</span></div>
  <form id="registry-form" class="registry-form"><div class="registry-search-wrap"><label class="field" for="registry-search">Organization, city or EIN</label><input class="search" id="registry-search" name="q" type="search" maxlength="160" placeholder="Try Wikimedia, food bank, climate, or an EIN…" autocomplete="off"></div><div><label class="field" for="registry-state">Filing-address location</label><select id="registry-state" name="state"><option value="">All locations</option>${Object.entries(registry.states).sort(([a],[b])=>(stateLabels[a]||a).localeCompare(stateLabels[b]||b)).map(([key,count])=>`<option value="${key}">${esc(stateLabels[key]||key)} · ${fmt(count)}</option>`).join('')}</select></div><div><label class="field" for="registry-cause">Cause classification</label><select id="registry-cause" name="cause"><option value="">All classifications</option>${Object.entries(registry.causes).sort(([a],[b])=>causeLabels[a].localeCompare(causeLabels[b])).map(([key,count])=>`<option value="${key}">${esc(causeLabels[key])} · ${fmt(count)}</option>`).join('')}</select></div><button class="button" type="submit">Search ↗</button></form>
  <div class="chips registry-examples"><span>Explore:</span>${['food bank','climate','legal aid','community','Wikimedia'].map(q=>`<button class="chip" data-example="${q}">${q}</button>`).join('')}<button class="chip" id="registry-clear">Clear filters</button></div>
  <p id="registry-status" role="status" aria-live="polite">Loading the registry…</p><div id="registry-results" aria-busy="true"></div><div id="registry-pages" class="registry-pagination" hidden><button class="small-button" id="registry-prev">← Previous</button><span id="registry-page-label"></span><button class="small-button" id="registry-next">Next →</button></div>
  <noscript><div class="callout">Interactive registry search needs JavaScript. You can <a href="${esc(registry.sourceUrl)}">download the original IRS files</a> or <a href="/data/">browse all 40 assessment profiles</a> without it.</div></noscript></section>
  <section class="registry-provenance"><div><div class="eyebrow">Coverage you can inspect</div><h2>Big index.<br>Clear boundaries.</h2></div><div><p>The September 8, 2026 IRS Business Master File contains ${fmt(registry.sourceRecordCount)} tax-exempt records. This index retains ${fmt(registry.recordCount)} unique 501(c)(3) organizations with unconditional or conditional exemption codes, including public charities, private foundations, schools and religious organizations. Identity is deduplicated by EIN.</p><p>This is an IRS registry, not a worldwide charity census. Some churches and self-declared organizations are absent from IRS extracts. Headquarters locations may differ from operating locations; NTEE classifications can be incomplete. Registration and reported financials do not measure systemic impact.</p><p><a href="${esc(registry.sourceUrl)}">Inspect the original IRS source ↗</a> · <a href="/api/v1/registry-manifest.json">Read the dated import manifest ↗</a> · <a href="/methodology/">How an assessment is built ↗</a></p></div></section>
  <dialog id="registry-detail" aria-labelledby="registry-detail-title"><div class="dialog-head"><h2 id="registry-detail-title"></h2><button class="icon-button" id="registry-detail-close" aria-label="Close registry record">×</button></div><div id="registry-detail-content"></div></dialog>`;
}
